test: main.c vec3.c init.c gaussseidel.c verlet.c fields.c constraints.c ./systems/npendulum.c 
	gcc main.c vec3.c init.c gaussseidel.c verlet.c fields.c constraints.c ./systems/npendulum.c -I ./include/ -lm	
