simulation : main.c vector.c manifold.c init.c ./systems/npendulum.c write.c gaussseidel.c fields.c verlet.c constraints.c     
	gcc main.c vector.c manifold.c init.c ./systems/npendulum.c write.c gaussseidel.c fields.c verlet.c constraints.c -I ./include/ -lm 
